version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=true
#      - N8N_BASIC_AUTH_USER=admin
#      - N8N_BASIC_AUTH_PASSWORD=admin123
      - GENERIC_TIMEZONE=America/Lima
#      - WEBHOOK_URL=https://slowly-fluid-jam-jill.trycloudflare.com/
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/node_modules/@custom-js/n8n-nodes-pdf-toolkit

    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - ollama
    restart: unless-stopped


  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped


networks:
  default:
    driver: bridge
 